---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: spectrum-inject
  name: spectrum-inject
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spectrum-inject
      name: spectrum-inject
    spec:
      containers:
        - name: webhook
          image: docker.io/kahmed0822/mutating-webhook:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: ALLOWED_NAMESPACES
            value: "proj-1 proj-2"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: webhook
  name: spectrum-webhook
spec:
  ports:
    - port: 443
      targetPort: 8080
  selector:
    app: spectrum-inject
